### ISSUE TITLE
Error when selecting Yes or No when confirming delete of venue

### ISSUE THREAD

**Issue by kana-ki** [FFXIVVenues/ffxiv-venues-veni#14]
When deleting a venue, Veni asks if you're sure if you want to delete the venue. 
However, when you select either the **Yes** button or **No** button, veni fails to respond to confirm. 

This is because veni throws an exception regarding a response already having being sent by this point. 
The venue is actually deleted behind the scenes however. 

**Update the `RespondAsync`'s to `FollowUpAsync` or `Channel.SendMessageAsync`**

**Comment by AllegroVivo** [comment]
✨ Hey, it works now! ✨
