### ISSUE TITLE
Add European Data Center worlds

### ISSUE THREAD

**Issue by kana-ki** [FFXIVVenues/ffxiv-venues-veni#17]
Currently when creating a venue with Veni, Veni will only list world in the North American data center. 

**Add options for worlds from the European Data Centers.**
Because Discord limits us to 25 items in a single drop down list, we'll need to split the question up to "Which Data Center?" and then "Which World?". 

- [ ] Split the question to separate Data Center and World questions
- [ ] Add European data centers and worlds

**Comment by sumi-satsuo** [comment]
You can also divide by asking the region first, then you can pbbly keep the same format if you prefer. But I personally prefer asking them the region and then also divide the next questions like you described
